name: Release Nightly

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build-n-release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --global mocha
      - run: npm i
      - run: ./soup.js -e require:process -p soup -i main.soup -o soup-node-${{ matrix.node-version }}.js
      - name: Setup artifacts
        uses: actions/upload-artifact@v2
        with:
          name: soup-nightly
          path: |
            soup-node-${{ matrix.node-version }}.js
      - name: Update nightly release
        if: success()
        uses: eine/tip@master
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: soup-node-${{ matrix.node-version }}.js